### ISSUE TITLE
Wrong/incomplete version number

### ISSUE THREAD

**Issue by keilw** [eclipse/microprofile-parent#4]
The version number just says  `<version>1-SNAPSHOT</version>` This looks very incomplete. Even if the parent was still intended for MP 1, there should at least be another digit like `1.0-SNAPSHOT` IMO (and that of common version schemes everywhere)

**Comment by ederks85** [comment]
+1. I noticed this as well

**Comment by keilw** [comment]
Guess you see how long this has been ignored ;-/

**Comment by radcortez** [comment]
Well this POM was never used. We intent to use it from now on.

This POM version does not have to align with MP version.
