### ISSUE TITLE
Should the parent pom be using Jakarta EE 9.0 or 9.1?

### ISSUE THREAD

**Issue by andymc12** [eclipse/microprofile-parent#47]
Per comment in https://github.com/eclipse/microprofile-rest-client/pull/319#discussion_r672699347, is this line correct? Or should it be 9.1.0?

https://github.com/eclipse/microprofile-parent/blob/a92901db14f74497a6c2c8188a376b1e446f5f8a/pom.xml#L39

Thanks!

**Comment by ederks85** [comment]
I also would expect 9.1 here

**Comment by Emily-Jiang** [comment]
good point. The parent pom was not updated after we decided to align with Jakarta EE 9.1. I'll update the parent pom shortly.

**Comment by Emily-Jiang** [comment]
I took a look at the pom.xml again and can confirm that line was not used anywhere. I have deleted it, as this version is only applicable to depend on jakarta.platform instead of the subset of the specs MicroProfile depends on.

**Comment by ederks85** [comment]
@Emily-Jiang in other words, the parent doesn't depend on a specific version of the Jakarta EE Platform. It doesn't contain this dependency, but the API's it supports. Fine with me, and with these changes it becomes clear how exactly MP "builds upon" the Jakarata EE Platform

**Comment by Emily-Jiang** [comment]
> @Emily-Jiang in other words, the parent doesn't depend on a specific version of the Jakarta EE Platform. It doesn't contain this dependency, but the API's it supports. Fine with me, and with these changes it becomes clear how exactly MP "builds upon" the Jakarata EE Platform

@ederks85 if you open the whole Jakarta EE platform api to MP, we will not be able to enforce only 5 Jakarta EE specs are pulled. Very soon, we might depend on Jakarta servlet for an example. Therefore, we only pull in 5 maven dependencies.

**Comment by ederks85** [comment]
That approach is perfectly clear to me now, thanks
