### ISSUE TITLE
Incorrect and missing license files

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-parent#50]
I noticed a couple of issues with the licenses:
1. the javadoc license uses Apache License instead of Eclipe Foundation license for final releases.
2. The license file was not made to the tck jars. See fault tolerance and jwt specs. 
@radcortez can you take a look?

**Comment by radcortez** [comment]
Ok, let me check.

**Comment by radcortez** [comment]
@Emily-Jiang were you running the final release locally? The parameter to change the license is `release.revision` now. In Jenkins the parameter is passed under the covers using the old `revremark`.

For JWT, everything seems to be ok. 

For Fault Tolerance, it is missing a `tck` marker file in `tck/src/main/resources/META-INF/`.

**Comment by Emily-Jiang** [comment]
@radcortez I updated the parent pom.xml `release.revision` to Final, but the apache license was copied instead of the EF license for the javadoc.
For JWT, I don't see the license files copied to any test jars.

**Comment by radcortez** [comment]
All licenses are copied to the javadocs folder (either in Draft or Final), the difference is the link in the javadoc html. For instance this is the log I get when running `mvn javadoc:javadoc -Drelease.revision=Final -X`:

```
[DEBUG]   (f) bottom = Copyright &#169; 2017 &#x2013; {currentYear} {organizationName}. All rights reserved.
                            <br>
                            Use is subject to <a href="{@docRoot}/licenses/efsl-1.0.html" target="_top">license terms</a>.
```

BTW, the `release.revision` is a property to activate the relevant profile to pick which license to use, but the property profile activation can only be done on the maven command (it doesn't work if you set the property inside the pom).

**Comment by Emily-Jiang** [comment]
@radcortez thanks for looking into it! Previously, I changed the `release.revision` to `Final` on the parent pom.xml and build the artifacts. I used the artifact on the sub project. Somehow, it did not work. I used what you suggested by passing in the property and it seems to work. I realised the missing licenses are for all jars if they are not in final release. In the previous relases, we used apache v2 for all of non-final releases. I think you only add licenses if the release is final. I think we need to add the corresponding licenses for non-final and final releases.

**Comment by radcortez** [comment]
> @radcortez thanks for looking into it! Previously, I changed the `release.revision` to `Final` on the parent pom.xml and build the artifacts. I used the artifact on the sub project. Somehow, it did not work. I used what you suggested by passing in the property and it seems to work.

Yes, because the licenses are changes with a profile, the profile cannot be activated with a property in the pom, since the reactor resolution needs to happen atomically and that creates a chicken / egg problem.

> I realised the missing licenses are for all jars if they are not in final release. In the previous relases, we used apache v2 for all of non-final releases. I think you only add licenses if the release is final. I think we need to add the corresponding licenses for non-final and final releases.

Let me check.

**Comment by radcortez** [comment]
Ok, so my understanding is that the API sources jar doesn't require any license change. It just uses whatever license it has set on the project: https://github.com/microprofile/microprofile-wg/issues/4#issuecomment-725506429

So a license is included (or not) if it is present in the project directly. If you revert JWT to a commit pre parent pom update and do the build, you will see that the API jar also has no license, because there is no licence file in the project sources.

**Comment by Emily-Jiang** [comment]
My understanding is that api and tck jars should contain Apache Licenses for non final releases. @kwsutter can you confirm whether my understanding is right?
