### ISSUE TITLE
This POM seems unused

### ISSUE THREAD

**Issue by keilw** [eclipse/microprofile-parent#9]
The current Parent POM:
https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.eclipse.microprofile%22%20AND%20a%3A%22microprofile%22 
is not based on this repository.

Are there plans to keep the artifactId `microprofile` or switch it to `microprofile-parent`?

**Comment by radcortez** [comment]
That is not the Parent POM. It is the Platform Release project.

Moving forward, the Platform Release Project will inherit the Parent POM from this repo.
